language: node_js
node_js:
  - "node"
branches:
  only:
    - master
git:
  branch: master
before_script:
  - git checkout master
script:
  - npm version patch -m "[CHORE] Bump Version %s [skip ci]"
before_deploy:
  - git push https://$GITHUB_TOKEN@github.com/DudeSolutions/autodude-webdriver master
  - git push https://$GITHUB_TOKEN@github.com/DudeSolutions/autodude-webdriver --tags
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: false
    branches:
      - master
