language: node_js
node_js:
  - "node"
branches:
  only:
    - master
git:
  branch: master
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: false
    branches:
      - master