language: node_js
node_js:
  - "node"
branches:
  only:
    - master
git:
  branch: master
script:
  - npm install
  - npm test
  - npm version patch -m "[CHORE] Bump Version %s [skip ci]"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: false
    branches:
      - master