package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.buildFeatures.merge
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_1.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Publish'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Publish")
    name = "Publish"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            name = "Setup Git Config"
            scriptMode = script {
                content = """
                    ${'$'}env:path += ";" + (Get-Item "Env:ProgramFiles").Value + "\Git\bin"
                    git config --global push.default simple
                    git config --global user.email "team.city@dudesoln.com"
                    git config --global user.name "Team City"
                """.trimIndent()
            }
        }
        powerShell {
            name = "NPM Version Patch"
            scriptMode = script {
                content = """npm version patch -m "[CHORE] Bump version %s""""
            }
        }
        powerShell {
            name = "Push"
            enabled = false
            scriptMode = script {
                content = """
                    ${'$'}env:path += ";" + (Get-Item "Env:ProgramFiles").Value + "\Git\bin"
                    
                    git push origin master
                    git push origin --tags
                """.trimIndent()
            }
        }
    }

    triggers {
        finishBuildTrigger {
            buildTypeExtId = "AutodudeWebdriver_Build"
        }
    }

    features {
        merge {
            branchFilter = "+:<default>"
            destinationBranch = "master"
        }
    }
}))

